# 面向对象编程
面向对象编程是一种编程思想。面向对象编程是从面向过程编程过渡来的。

## 以洗衣服作为一个案例
### 面向过程编程
如果用面向过程的编程思想，我们将洗衣服拆解成一系列步骤，每个步骤就是一个函数。<br>
```第一步```: 打开洗衣机；<br>
```第二步```: 放衣服和洗衣液；<br>
```第三步```: 选择洗衣模式，开始洗衣服；<br>
```第四步```: 等待洗完，拿出衣服。<br>

### 面向对象编程
拆分人和洗衣机两个对象：<br>
#### 人
```第一步```: 打开洗衣机；<br>
```第二步```: 放衣服和洗衣液；<br>
```第三步```: 洗完衣服后拿出衣服；<br>
#### 洗衣机
```第一步```: 根据洗衣模式洗衣服；<br>

### 总结
* 面向过程编程：更注重事情的每个步骤以及顺序
* 面向对象编程：更注重事情有哪些参与者，参与者需要做些什么事情。将其拆解成一个个模块和对象。

## 用一个简单的例子来通俗地解释面向对象编程（Object-Oriented Programming，简称OOP）。

想象一下，你正在玩一个电子游戏，游戏里有很多角色，比如战士、法师和弓箭手。每个角色都有他们自己的属性（比如生命值、攻击力）和技能（比如战士的剑击、法师的火球术、弓箭手的箭雨）。在面向对象编程中，我们可以把每个角色看作是一个“对象”。

### 1. 什么是“对象”？

在面向对象编程的世界里，“对象”就像是现实世界中的事物。每个对象都有自己的“属性”（就像是事物的特性）和“方法”（就像是事物能做的事情）。比如，一辆车是一个对象，它有颜色（属性）和启动（方法）。

### 2. 什么是“类”？

“类”就像是对象的“蓝图”或“模板”。通过这个蓝图，我们可以创建很多相似的对象。比如，我们有一个“角色”类，它定义了所有角色共有的属性和方法。然后，我们可以用这个类来创建具体的战士、法师和弓箭手对象。

### 3. 面向对象编程的好处

- **封装**：每个对象都把自己的数据（属性）和操作数据的方法（行为）封装在一起，这样可以保护数据不被随意访问和修改。
- **继承**：我们可以创建新的类来继承已有类的属性和方法，这样可以减少重复代码，让编程更高效。
- **多态**：不同的对象可以对同一个方法有不同的响应，这让程序更灵活。

### 总结

面向对象编程就像是在用代码创造一个虚拟世界，你定义了各种“类”（蓝图），然后根据这些蓝图创建具体的“对象”（实例）。每个对象都有自己的属性和方法，就像是每个角色都有自己的生命值和技能。通过这种方式，我们可以更自然地模拟现实世界的复杂性，并且让代码更加模块化、易于理解和维护。


# 面向对象程序设计-类(Class)
类是封装对象的属性和行为的载体，也就是说具有相同属性和行为的一类实体被称为类。

列表实际上是列表类，也就是封装了列表操作的类，它提供了一系列方法来操作列表中的元素。

In [8]:
list1 = ['banana', 'apple', 'cherry']
list1.append('cherry')
print(list1)
list1.sort()
print(list1)

['banana', 'apple', 'cherry', 'cherry']
['apple', 'banana', 'cherry', 'cherry']


In [7]:
class Consumer:
    def __init__(self, w):
        self.wealth = w

    def earn(self, y):
        self.wealth += y

    def spend(self, x):
        new_wealth = self.wealth - x
        if new_wealth < 0:
            print("Insufficent Funds")
        else:
            self.wealth = new_wealth

    def __str__(self):
        return f"Consumer: wealth={self.wealth}"

In [8]:
c1 = Consumer(10)
c1.earn(5)
c1.spend(3)
c1.wealth

12

# 类的魔法方法
Python 中的魔法方法，也称为特殊方法或双下方法，是一些具有特殊名称的方法，它们在特定的操作或内置函数调用时被自动调用。这些方法的名称以双下划线开头和结尾，例如 __init__ 或 __str__。它们允许开发者定义或修改类的默认行为。

## _str_方法
当你在Python中使用print()函数打印一个对象，或者使用str()函数将对象转换为字符串时，__str__方法就会被触发。这个方法应该返回一个字符串，这个字符串描述了对象的状态或内容。

In [26]:
class Consumer:
    def __init__(self, w):
        self.wealth = w

    def earn(self, y):
        self.wealth += y

    def spend(self, x):
        new_wealth = self.wealth - x
        if new_wealth < 0:
            print("Insufficent Funds")
        else:
            self.wealth = new_wealth

    def __str__(self):
        return f"Consumer: wealth={self.wealth}"

In [28]:
c1 = Consumer(10)
c1.earn(5)
c1.spend(3)
print(c1)

Consumer: wealth=12


## _call_方法
在Python中，__call__方法是一个特殊方法，它允许一个类的实例表现得像一个函数。当你调用一个对象时（即使用圆括号()），如果该对象的类定义了__call__方法，那么这个方法就会被执行。这使得对象可以像函数那样被“调用”。

In [29]:
class Consumer:
    def __init__(self, w):
        self.wealth = w

    def earn(self, y):
        self.wealth += y

    def spend(self, x):
        new_wealth = self.wealth - x
        if new_wealth < 0:
            print("Insufficient Funds")
        else:
            self.wealth = new_wealth

    def __call__(self, action=None, amount=0):
        if action is None:
            return str(self)
        elif action == 'earn' and amount >= 0:
            self.earn(amount)
        elif action == 'spend' and amount > 0:
            self.spend(amount)
        else:
            print("Invalid action or amount")
    
    def __str__(self):
        return f"Consumer: wealth={self.wealth}"

In [30]:
c1 = Consumer(100)
print(c1)  # 打印当前财富
c1('spend', 5)  # 花费50
print(c1)  # 打印更新后的财富
c1('earn', 2)  # 赚取20
print(c1)  # 打印更新后的财富
c1('spend', 200)  # 尝试花费200，超过当前财富

Consumer: wealth=100
Consumer: wealth=95
Consumer: wealth=97
Insufficient Funds


## _len_方法

In [32]:
class Consumer:
    def __init__(self, w):
        self.wealth = w

    def earn(self, y):
        self.wealth += y

    def spend(self, x):
        new_wealth = self.wealth - x
        if new_wealth < 0:
            print("Insufficient Funds")
        else:
            self.wealth = new_wealth

    def __str__(self):
        return f"Consumer: wealth={self.wealth}"

    def __len__(self):
        # 返回财富的绝对值的位数
        return len(str(abs(self.wealth)))

In [34]:
c1 = Consumer(100)
print(len(c1))  # 输出财富的位数
c1.earn(200)
print(len(c1))  # 输出更新后的财富的位数
c1.spend(250)
print(len(c1))  # 输出更新后的财富的位数

3
3
2


## 创建一个类
### 一个市场
```线性需求函数```: $Q^d = ap + b$ <br>
```线性供给函数```: $Q^s = cp + d$ <br>
<img src="figure/figure1.jpg" alt="示例图片" width="700" height="500">


1. 求解市场的短期均衡价格和均衡产量。<br>
* 均衡价格：<br>
$$
\begin{align*}
ap + b &= cp + d \\
(a - c)p &= (d - b) \\
p^* &= \dfrac{d - b}{a - c}
\end{align*}
$$
* 均衡产量：<br>
$$q^*=ap^*+b$$

2. 该市场的消费者剩余、生产者剩余和社会总福利分别是多少？
* 消费者剩余：<br>

$$consumer_{surp}=(-\dfrac{b}{a}-p^*)\times q^* \times \dfrac{1}{2}$$
* 生产者剩余：<br>
$$producer_{surp}=[p^*-(-\dfrac{d}{c})]\times q^*\times \dfrac{1}{2}$$
* 社会总福利：<br>
$$total_{surp}=consumer_{surp}+producer_{surp}$$

In [40]:
class Market:
    def __init__(self, a, b, c, d):
         '''
         设置市场参数
         '''
         self.a, self.b, self.c, self.d = a, b, c, d
         if -b/a < -d/c:
              raise ValueError('Insufficient demand')
     
    def price(self):
         "计算均衡价格"
         return (self.d - self.b) / (self.a - self.c)
    
    def quantity(self):
         "计算均衡数量"
         return self.a * self.price() + self.b
    
    def consumer_surp(self):
         "计算消费者剩余"
         return (-self.b/self.a - self.price()) * self.quantity() * 0.5
    
    def producer_surp(self):
         "计算厂商剩余"
         return (self.price() + self.d/self.c) * self.quantity() * 0.5
    def total_surp(self):
         return self.producer_surp() + self.consumer_surp()
    

In [41]:
baseline_params = -4, 68, 4, -12
m = Market(*baseline_params)
print(m.price())
print(m.quantity())
print(m.consumer_surp())
print(m.producer_surp())


10.0
28.0
98.0
98.0


## 封装
封装是面向对象编程的核心思想，将对象的属性和行为封装起来。将对象的属性和行为封装起来的载体就是类，类通常对使用者隐藏其实现细节。

### 函数的封装

In [2]:
# 定义一个3x4矩阵
matrix_a = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

# 定义一个4x3矩阵
matrix_b = [
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21],
    [22, 23, 24]
]

# 初始化结果矩阵为一个3x3的零矩阵
result = [[0 for i in range(3)] for i in range(3)]

# 计算结果矩阵
for i in range(3):  # 遍历matrix_a的行
    for j in range(3):  # 遍历matrix_b的列
        for k in range(4):  # 遍历matrix_a的列和matrix_b的行
            result[i][j] += matrix_a[i][k] * matrix_b[k][j]

print(result)

[[190, 200, 210], [470, 496, 522], [750, 792, 834]]


In [38]:
def matrix_multiply(matrix_a, matrix_b):
    # 检查矩阵是否可以相乘
    if len(matrix_a[0]) != len(matrix_b):
        raise ValueError("The number of columns in the first matrix must be equal to the number of rows in the second matrix.")

    # 初始化结果矩阵为一个零矩阵
    result = [[0 for _ in range(len(matrix_b[0]))] for _ in range(len(matrix_a))]

    # 计算结果矩阵
    for i in range(len(matrix_a)):  # 遍历matrix_a的行
        for j in range(len(matrix_b[0])):  # 遍历matrix_b的列
            for k in range(len(matrix_b)):  # 遍历matrix_a的列和matrix_b的行
                result[i][j] += matrix_a[i][k] * matrix_b[k][j]

    return result

In [39]:
# 定义一个3x4矩阵
matrix_a = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

# 定义一个4x3矩阵
matrix_b = [
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21],
    [22, 23, 24]
]

# 调用函数并打印结果
result = matrix_multiply(matrix_a, matrix_b)
print(result)

[[190, 200, 210], [470, 496, 522], [750, 792, 834]]


导入numpy模块--shell命令

In [5]:
! pip install numpy

In [42]:
import numpy as np

# 定义矩阵
matrix_a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

matrix_b = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21],
    [22, 23, 24]
])

# 使用numpy.dot()进行矩阵乘法
result = np.dot(matrix_a, matrix_b)

print(result)


[[190 200 210]
 [470 496 522]
 [750 792 834]]


## 继承
理解：继承是我们每个人都从祖辈和父辈那边继承了一些体貌特征，但是每个人却又有不同于父母，因为每个人都存在一些自己的特性，这些特性是独有的，在父母身上没有体现。

* 在程序设计中实现继承，表示这个类拥有它继承的类的所有公有成员或者受保护成员。
* 在面向对象编程中，被继承的类被称为父类，新的类被称为子类。

<img src="figure/figure2.png" alt="示例图片" width="700" height="500">

* 虽然子类没有定义_init_方法，但是父类有，所以在子类继承父类的时候这个方法就被继承了。
* 子类在继承的时候，在定义类时，小括号（）为父类的名字。

### 单继承
单继承就是子类会有一个父类，并且具有他们的特性。

### 政府对市场征税
3. 如果政府对每一单位商品征收t元的税，那么该市场的短期均衡价格和均衡产量是多少？另外，消费者剩余、生产者剩余和社会总福利的变化又分别是多少？<br>
```线性需求函数```: $Q^d = ap + b$ <br>
```线性供给函数```: $Q^s = c(p-t) + d$ <br>
* 均衡价格<br>
$$
\begin{align*}
ap + b &= c(p - t) + d \\
p^{**} &= \dfrac{d - b - ct}{a - c}
\end{align*}
$$
* 均衡产量<br>
$$q^{**} = ap^{**}+b$$
* 消费者剩余<br>
$$consumer_{surp}=(-\dfrac{b}{a}-p^{**})\times q^{**} \times \dfrac{1}{2}$$
* 生产者剩余：<br>
$$producer_{surp}=[p^{**}-(-\dfrac{d}{c})-t]\times q^{**}\times \dfrac{1}{2}$$
* 社会总福利：<br>
$$total_{surp}=consumer_{surp}+producer_{surp}$$


In [ ]:
class Market:
    def __init__(self, a, b, c, d):
         '''
         设置市场参数
         '''
         self.a, self.b, self.c, self.d = a, b, c, d
         if -b/a < -d/c:
              raise ValueError('Insufficient demand')
     
    def price(self):
         "计算均衡价格"
         return (self.d - self.b) / (self.a - self.c)
    
    def quantity(self):
         "计算均衡数量"
         return self.a * self.price() + self.b
    
    def consumer_surp(self):
         "计算消费者剩余"
         return (-self.b/self.a - self.price()) * self.quantity() * 0.5
    
    def producer_surp(self):
         "计算厂商剩余"
         return (self.price() + self.d/self.c) * self.quantity() * 0.5
    def total_surp(self):
         return self.producer_surp() + self.consumer_surp()
    
class TaxedMarket(Market):
    def __init__(self, a, b, c, d, tax):
        super().__init__(a, b, c, d)
        self.t = tax
    
    def price(self):
        "计算含税均衡价格"
        return (self.d - self.b - self.c * self.t ) / (self.a - self.c)
    
    def producer_surp(self):
        "计算含税厂商剩余"
        # 厂商剩余需要考虑税收影响，因此价格应该是不含税的价格
        return (self.price() + self.d/self.c - self.t) * self.quantity() * 0.5


In [49]:
baseline_params = -4, 68, 4, -12, 2
m = TaxedMarket(*baseline_params)
print(m.price())
print(m.quantity())
print(m.consumer_surp())
print(m.producer_surp())

11.0
24.0
72.0
72.0


### 多继承
多继承就是子类有2个或2个以上父类，并且具有他们的特性。<br>
<img src="figure/figure4.png" alt="示例图片" width="700" height="500">

In [ ]:
class Market:
    def __init__(self, a, b, c, d):
        '''
        设置市场参数
        '''
        self.a, self.b, self.c, self.d = a, b, c, d
        if -b/a < -d/c:
            raise ValueError('Insufficient demand')
    
    def price(self):
        "计算均衡价格"
        return (self.d - self.b) / (self.a - self.c)
    
    def quantity(self):
        "计算均衡数量"
        return self.a * self.price() + self.b
    
    def consumer_surp(self):
        "计算消费者剩余"
        return (-self.b/self.a - self.price()) * self.quantity() * 0.5
    
    def producer_surp(self):
        "计算厂商剩余"
        return (self.price() + self.d/self.c) * self.quantity() * 0.5
    
    def total_surp(self):
        return self.producer_surp() + self.consumer_surp()

In [2]:
class TaxedMarketBase:
    def __init__(self, tax):
        self.t = tax

    def producer_surp(self, quantity, price):
        "计算含税厂商剩余"
        # 厂商剩余需要考虑税收影响，因此价格应该是不含税的价格
        return (price + self.d/self.c - self.t) * quantity * 0.5

继承上面两个父类的子类

In [ ]:
class TaxedMarket(Market, TaxedMarketBase):
    def __init__(self, a, b, c, d, tax):
        Market.__init__(self, a, b, c, d)
        TaxedMarketBase.__init__(self, tax)
    
    def price(self):
        "计算含税均衡价格"
        return (self.d - self.b - self.c * self.t) / (self.a - self.c)
    
    def producer_surp(self):
        "计算含税厂商剩余"
        return TaxedMarketBase.producer_surp(self, self.quantity(), self.price())

In [51]:
baseline_params = -4, 68, 4, -12, 2
m = TaxedMarket(*baseline_params)
print(m.price())
print(m.quantity())
print(m.consumer_surp())
print(m.producer_surp())

11.0
24.0
72.0
72.0


* 子类在继承的时候，在定义类时，小括号内部（）为父类的名字。父类有多个。

## 多态
一个父类有多个子类

### 一个市场
```市场线性需求函数：```$P(Q)=aQ+b$<br>
```企业的线性成本函数:```$C(Q)=cQ$

1. 完全竞争市场
* 利润函数：
$$\pi(Q)=PQ-C$$
* 利润最大化：<br>
$$
\begin{align*}
\dfrac{d \pi(Q)}{d Q} = P(Q) - \dfrac{dC(Q)}{dQ} &=0 \\
P^* &= \dfrac{dC(Q)}{dQ}
\end{align*}
$$


In [57]:
class Market:
    def __init__(self, a, b, c):
        self.a, self.b, self.c = a, b, c


* 利润最大化时候的产量：<br>
\begin{align*}
P^* &= aQ^* + b \\
Q^* &= \frac{P^* - b}{a}
\end{align*}
$$

In [58]:
class PerfectCompetitionMarket(Market):
    def price(self):
        # 在完全竞争市场中，均衡价格等于边际成本
        return self.c

    def quantity(self):
        # 均衡产量由市场需求函数决定，P = MC
        return ( self.price() - self.b) / self.a

In [73]:
# 参数设置
a = -1  # 需求函数中的a
b = 100    # 需求函数中的b
c = 4    # 成本函数中的c

# 创建市场实例
perfect_competition_market = PerfectCompetitionMarket(a, b, c)
print(perfect_competition_market.price())
print(perfect_competition_market.quantity())

4
96.0


2. 古诺均衡<br>
两个厂商都是已知对方产量的情况下，各自确定能够给自己带来最大利润的产量（每一个厂商都是以自己的产量去适应对方已确定的产量）。<br>
$$Q = Q_1 +  Q_2$$
```市场线性需求函数：```$P(Q_1,Q_2)=a(Q_1+Q_2)+b$<br>
```企业的线性成本函数:```$C(Q_1,Q_2)=c(Q_1+Q_2)$


* 在确定厂商$Q_2$的条件下，求$Q_1$:<br>
* 利益函数：
 $$\pi(Q_1)=P(Q_1,Q_2)Q_1-c(Q_1)$$
$$\dfrac{d \pi(Q_1,Q_2)}{d Q_1}=\dfrac{d P(Q_1,Q_2)}{d Q_1}Q_1+P(Q_1,Q_2)-c=0$$
$$aQ_1+P(Q_1,Q_2)-c=0$$
$$Q_1=\dfrac{c-b-aQ_2}{2a}$$
* 在确定厂商$Q_1$的条件下，求$Q_2$:<br>
$$Q_2=\dfrac{c-b-aQ_1}{2a}$$

In [70]:
class CournotMarket(Market):
    def price(self):
        # 古诺均衡价格计算
        q1, q2 = self.quantity()
        total_quantity = q1 + q2
        return self.a * total_quantity + self.b

    def quantity(self):
        # 古诺均衡产量计算
        # 假设两个企业对称，成本相同
        q1 = q2 = (self.c - self.b)/(3 * self.a)
        return q1, q2


In [64]:
# 参数设置
a = -1  # 需求函数中的a
b = 100    # 需求函数中的b
c = 4    # 成本函数中的c
cournot_market = CournotMarket(a, b, c)
print(cournot_market.price())
print(cournot_market.quantity())

36.0
(32.0, 32.0)


* 卡特尔均衡<br>
两个厂商联合起来，实现市场上的利润最大化。
$$Q_1=Q_2$$
* 利益函数：
$$\pi(Q_1,Q_2)=P(Q_1,Q_2)(Q_1+Q_2)-c(Q_1+Q_2)$$
$$\dfrac{\partial \pi(Q_1,Q_2)}{\partial Q_1}=\dfrac{\partial P(Q_1,Q_2)}{\partial Q_1}(Q_1+Q_2)+P(Q_1,Q_2)-c=0$$
$$Q_1+Q_2=\dfrac{c-b}{2a}$$

In [71]:
class CartelMarket(Market):
    def price(self):
        # 卡特尔均衡价格计算
        q1, q2 = self.quantity()
        total_quantity = q1 + q2
        return self.a * total_quantity + self.b

    def quantity(self):
        # 卡特尔均衡产量计算
        # 总产量使得价格最大化
        q1 = q2 = (self.c - self.b)/(4 * self.a)
        return q1, q2

In [72]:
# 参数设置
a = -1  # 需求函数中的a
b = 100    # 需求函数中的b
c = 4    # 成本函数中的c
cartel_market = CartelMarket(a, b, c)
print(cartel_market.price())
print(cartel_market.quantity())


52.0
(24.0, 24.0)
